name: Release

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    Build:
        name: Build Equicord
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3

            - name: Use Node.js 24
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build web
              run: pnpm buildWebStandalone

            - name: Build
              run: pnpm buildStandalone

            - name: Generate plugin lists
              run: |
                  pnpm generatePluginJson dist/plugins.json
                  pnpm generateEquicordPluginJson dist/equicordplugins.json
                  pnpm generateVencordPluginJson dist/vencordplugins.json
                  pnpm generateDevsList dist/devs.json

            - name: Collect files
              run: |
                  cd dist
                  mkdir release
                  cp browser/browser.* release
                  cp Equicord.user.{js,js.LEGAL.txt} release
                  cp *.{json,zip,asar} release
                  cp desktop/* release
                  for file in equibop/*; do
                    filename=$(basename "$file")
                    cp "$file" "release/equibop${filename^}"
                  done

            - name: Create Release in devbuild repo
              uses: softprops/action-gh-release@v2
              with:
                  repository: realmort/Equicord-devbuild
                  tag_name: latest
                  name: Latest Build
                  files: dist/release/*
                  overwrite_files: true
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
