name: Build Branches
on:
    push:
        branches:
            - "**"
    workflow_dispatch:
        inputs:
            branch:
                type: choice
                description: "Branch to build and upload"
                options:
                    - main
                    - dev
                    - translation
                default: "dev"
env:
    FORCE_COLOR: true
    REPO: realmort/Equibored
    USERNAME: GitHub-Actions
permissions:
    contents: write
jobs:
    Build:
        name: Build Equicord
        runs-on: ubuntu-latest
        if: github.repository == 'realmort/Equicord'
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.branch || github.ref }}
            - uses: pnpm/action-setup@v3
              if: github.ref_name != 'bun'
            - name: Use Node.js 24
              if: github.ref_name != 'bun'
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  cache: "pnpm"
            - name: Install dependencies
              if: github.ref_name != 'bun'
              run: pnpm install --frozen-lockfile
            - name: Build web
              if: github.ref_name != 'bun'
              run: pnpm buildWebStandalone
            - name: Build
              if: github.ref_name != 'bun'
              run: pnpm buildStandalone
            - name: Generate plugin lists
              if: github.ref_name != 'bun'
              run: |
                  pnpm generatePluginJson dist/plugins.json
                  pnpm generateEquicordPluginJson dist/equicordplugins.json
                  pnpm generateVencordPluginJson dist/vencordplugins.json
                  pnpm generateDevsList dist/devs.json
            - uses: oven-sh/setup-bun@v2
              if: github.ref_name == 'bun'
              with:
                  bun-version: latest
            - name: Install dependencies
              if: github.ref_name == 'bun'
              run: bun install
            - name: Build web
              if: github.ref_name == 'bun'
              run: bun run buildWebStandalone
            - name: Build
              if: github.ref_name == 'bun'
              run: bun run buildStandalone
            - name: Generate plugin lists
              if: github.ref_name == 'bun'
              run: |
                  bun run generatePluginJson dist/plugins.json
                  bun run generateEquicordPluginJson dist/equicordplugins.json
                  bun run generateVencordPluginJson dist/vencordplugins.json
                  bun run generateDevsList dist/devs.json
            - name: Collect files to be released
              run: |
                  cd dist
                  mkdir release
                  cp browser/browser.* release
                  cp Equicord.user.{js,js.LEGAL.txt} release
                  cp *.{json,zip,asar} release
                  cp desktop/* release
                  for file in equibop/*; do
                    filename=$(basename "$file")
                    cp "$file" "release/equibop${filename^}"
                  done
                  find release -size 0 -delete
                  rm release/package.json
                  rm release/*.map
            - name: Upload Equicord Stable
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
                  git_hash=$(git rev-parse --short HEAD)
                  gh release delete latest --yes 2>/dev/null || true
                  gh release create latest --title "Equicord $git_hash" --notes "" dist/release/*
